Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<uuid:pk>/', views.cart_add, name='cart_add'),
    path('remove/<uuid:pk>/', views.cart_remove, name='cart_remove'),
]

ISQA3900Group8/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('', include('Nile.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}), #serve static files when deployed
]

Nile/urls.py
from django.urls import path, re_path, include
from django.views.static import serve

from Nile import views
from django.conf.urls.static import static
from django.conf import settings
from .views import CategoryList, subcategory_detail

app_name = 'Nile'

urlpatterns = [
    path('', views.index, name='index'),
    path('order/create/', views.order_create, name='order_create'),
    path('order/list/', views.orders_list, name='order_list'),
    path('Nile/admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('Nile/admin/order/pdf/<int:order_id>/', views.admin_order_pdf, name='admin_order_pdf'),
    path('item/create/', views.ItemCreate.as_view(), name='item_create'),
    path('item/<int:pk>/update/', views.ItemCreate.as_view(), name='item_update'),
    path('product/<uuid:pk>/detail/', views.ProductDetail, name='item_detail'),
    path('category/<int:pk>/detail/', views.CategoryDetail.as_view(), name='category_detail'),
    path('category_list/', views.CategoryList.as_view(), name='category_list'),
    path('subcategory_detail/<int:subcategory_id>/', subcategory_detail, name='subcategory_detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

Cart/models.py
from django.db import models

# Create your models here.

Cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    def __init__(self, *args, **kwargs):
        try:  # if choices provided
            mychoices = kwargs.pop('my_choices')
            super(CartAddProductForm, self).__init__(*args, **kwargs)
            self.fields["quantity"] = forms.TypedChoiceField(choices=mychoices,
                                                             coerce=int)
        except:  # use default of 21 if choices not provided
            super(CartAddProductForm, self).__init__(*args, **kwargs)
            self.fields["quantity"] = forms.TypedChoiceField(choices=[(i, str(i)) for i in range(1, 21)],
                                                             coerce=int)

    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

Cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Nile.models import Item
from .cart import Cart
from .forms import CartAddProductForm


@require_POST
def cart_add(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Item, pk=pk)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 update_quantity=cd['update'])
    return redirect('cart:cart_detail')


def cart_remove(request, pk):
    cart = Cart(request)
    product = get_object_or_404(Item, pk=pk)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        product = get_object_or_404(Item, id=item['product'].id)
        choices = [(i, str(i)) for i in range(1, product.quantity + 1)]
        item['update_quantity_form'] = CartAddProductForm(my_choices=choices,
                                                          initial={'quantity': item['quantity'],
                                                                   'update': True})
    return render(request, 'cart/detail.html', {'cart': cart})

Cart/templates/cart/detail.html
{% extends "Nile/base.html" %}
{% load static %}

{% block title %}
  Your shopping cart
{% endblock %}

{% block content %}
  <h1>Your Shopping Cart</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Image</th>
        <th>Product</th>
        <th>Quantity</th>
        <th>Remove</th>
        <th>Unit price</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      {% for cart_item in cart %}
        {% with item=cart_item.product %}
          <tr>
            <td>
              <a href="{{ item.product.get_absolute_url }}">
                <img src="{{ item.image.url }}" alt="avatar" style="width:25%">
              </a>
            </td>
            <td>{{ item.name }}</td>
            <td>
              <form action="{% url "cart:cart_add" item.id %}" method="post">
                {{ cart_item.update_quantity_form.quantity }}
                {{ cart_item.update_quantity_form.update }}
                <input type="submit" value="Update">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url "cart:cart_remove" item.id %}">Remove</a></td>
            <td class="num">${{ item.price }}</td>
            <td class="num">${{ cart_item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
    <br>
    <hr>
      <form action="{% url "Nile:index" %}" class="col-md-4">
        <button type="submit">Continue Shopping</button>
      </form>
      <form action="{% url "Nile:order_create" %}" class="col-md-4 pull-right">
       <button type="submit">Checkout</button>
         {% csrf_token %}
      </form>


{% endblock %}