Cart/urls.py
from django.urls import path
from . import views

app_name = 'Cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<uuid:pk>/', views.cart_add, name='cart_add'),
    path('remove/<uuid:pk>/', views.cart_remove, name='cart_remove'),
]

ISQA3900Group8/urls.py
from django.contrib.auth import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.static import serve
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('Cart.urls', namespace='cart')),
    path('', include('Nile.urls')),
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('register.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root':settings.MEDIA_ROOT}), #serve media files when deployed
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root':settings.STATIC_ROOT}), #serve static files when deployed
]

Nile/urls.py
from django.urls import path, re_path, include
from django.views.static import serve

from Nile import views
from django.conf.urls.static import static
from django.conf import settings
from .views import CategoryList, subcategory_detail

app_name = 'Nile'

urlpatterns = [
    path('', views.index, name='index'),
    path('order/create/', views.order_create, name='order_create'),
    path('order/list/', views.orders_list, name='order_list'),
    path('Nile/admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('Nile/admin/order/pdf/<int:order_id>/', views.admin_order_pdf, name='admin_order_pdf'),
    path('item/create/', views.ItemCreate.as_view(), name='item_create'),
    path('item/<int:pk>/update/', views.ItemCreate.as_view(), name='item_update'),
    path('product/<uuid:pk>/detail/', views.ProductDetail, name='item_detail'),
    path('category/<int:pk>/detail/', views.CategoryDetail.as_view(), name='category_detail'),
    path('category_list/', views.CategoryList.as_view(), name='category_list'),
    path('subcategory_detail/<int:subcategory_id>/', subcategory_detail, name='subcategory_detail'),
    path('accounts/', include('django.contrib.auth.urls')),
    re_path(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT})
    ] + static(settings.MEDIA_URL,
                         document_root=settings.MEDIA_ROOT)

Nile/models.py
import uuid
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
# Add PAYMENT METHOD and ADDRESS when we get to the point we introduce shopping cart sessions
# All the USER and USER_LOGIN information should be included in the django USER model

class Item(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image = models.ImageField(upload_to='media/images/', null=True, blank=True)
    quantity = models.PositiveIntegerField(default=0)
    # foreign key to the category table
    category = models.ForeignKey('Category', on_delete=models.RESTRICT, null=True)
    subcategory = models.ForeignKey('SubCategory', on_delete=models.RESTRICT, null=True, blank=True)


    ITEM_AVAILABILITY = (
        ('a', 'Available'),
        ('o', 'Out of Stock'),
    )

    availability = models.CharField(
        max_length=1,
        choices=ITEM_AVAILABILITY,
        blank=True,
        default='a',
    )

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'

    def get_absolute_url(self):
        """Returns the URL to access a particular item instance."""
        return reverse('item_detail', args=[str(self.id)])


class Category(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    name = models.CharField(max_length=200)
    description = models.TextField(max_length=1000)
    image = models.ImageField(upload_to='images/', null=True, blank=True)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.name}'

    def get_absolute_url(self):
        """Returns the URL to access a particular category instance."""
        return reverse('category_detail', args=[str(self.id)])


class SubCategory(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=50)
    categories = models.ManyToManyField(Category)

    def __str__(self):
        return self.name


class Order(models.Model):
    first_name = models.CharField(max_length=50, null=True)
    last_name = models.CharField(max_length=50, null=True)
    email = models.EmailField(null=True)
    address = models.CharField(max_length=250, null=True)
    postal_code = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=100, null=True)
    created = models.DateTimeField(auto_now_add=True, null=True)
    updated = models.DateTimeField(auto_now=True, null=True)
    paid = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True, related_name='order_user')

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order,
                              related_name='items',
                              on_delete=models.CASCADE)
    product = models.ForeignKey(Item,
                                related_name='order_items',
                                on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

Nile/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address',
                  'postal_code', 'city']

Nile/views.py
import random

from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from Cart.cart import Cart
from Cart.forms import CartAddProductForm
from .forms import OrderCreateForm
from .models import Item, Category, Order, OrderItem, SubCategory
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import Http404


def index(request):
    """View function for home page of site."""
    available_item_ids = Item.objects.filter(availability="a").values_list('id', flat=True)
    randomized_item_ids = random.sample(list(available_item_ids), min(len(available_item_ids), 25))
    recommended_items = Item.objects.filter(id__in=randomized_item_ids)

    context = {
        'recommended_items': recommended_items
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'Nile/index.html', context=context)


class ItemCreate(CreateView):
    model = Item
    fields = ['id', 'name', 'description', 'price', 'image', 'quantity', 'category', 'subcategory']


class ItemUpdate(UpdateView):
    model = Item
    fields = ['id', 'name', 'description', 'price', 'image', 'quantity', 'category', 'subcategory']


def ProductDetail(request, pk):
    product = get_object_or_404(Item, pk=pk)
    # set choices for quantity available based on inventory and items in this session's cart
    cart = Cart(request)
    cartquantity = 0
    # if item in cart, subtract the items in the cart from the quantity available
    for item in cart:
        cartproduct = get_object_or_404(Item, id=item['product'].id)
        if product == cartproduct:
            cartquantity = item['quantity']
            break
    if product.quantity - cartquantity > 0:
        choices = [(i, str(i)) for i in range(1, product.quantity - cartquantity + 1)]
    else:  # no items left in inventory for this session
        choices = [(1, 0)]

    cart_product_form = CartAddProductForm(my_choices=choices)
    return render(request, 'Nile/item_detail.html',
                  {'item': product,
                   'subcategory': SubCategory,
                   'cart_product_form': cart_product_form,
                   'cart': cart})


class CategoryDetail(DetailView):
    model = Category

def category_detail(request, category_id):
    category = SubCategory.objects.get(pk=category_id)
    items = Item.objects.filter(subcategory__category=category)
    return render(request, 'Nile/category_detail.html', {'category': category, 'items': items})


class CategoryList(ListView):
    model = Category


@login_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'Nile/admin/order/pdf.html',
                  {'order': order})


@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request,
                  'Nile/admin/order/detail.html',
                  {'order': order})


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            order.user_id = request.user.id
            order.save()
            print(order.user_id)
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity']
                                         )
                # reduce the number of items in inventory based on this sale
                item['product'].quantity = item['product'].quantity - item['quantity']
                item['product'].save()
            # clear the cart
            cart.clear()
            # set the order in the session
            request.session['order_id'] = order.id

            return render(request, 'Nile/order_created.html', {'order_id': order.id})
    else:
        form = OrderCreateForm()
    return render(request,
                  'Nile/order_create.html',
                  {'cart': cart, 'form': form})


@login_required
def orders_list(request):
    user = request.user

    orders = Order.objects.filter(user_id=user.id)

    context = {
        'orders': orders
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'Nile/order_list.html', context=context)


def subcategory_detail(request, subcategory_id):
    try:
        subcategory = get_object_or_404(SubCategory, pk=subcategory_id)
        items = Item.objects.filter(subcategory=subcategory, availability='a')

        context = {
            'subcategory': subcategory,
            'items': items,
        }

        return render(request, 'Nile/subcategory_detail.html', context)

    except SubCategory.DoesNotExist:
        raise Http404("SubCategory does not exist")

Nile/templates/Nile/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Nile{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <style>
        /* background color */
        .navbar-custom {
            background-color: #0F160C;
        }

        /* brand and text color */
        .navbar-custom .navbar-brand,
        .navbar-custom .navbar-text {
            color: #E9EEE7;
        }

        /* sidebar style */
        #mySidenav {
            height: 100%;
            width: 0;
            position: fixed;
            z-index: 1;
            top: 0;
            left: 0;
            background-color: #b7b9b6;
            overflow-x: hidden;
            transition: 0.5s;
            padding-top: 60px;
        }

        #mySidenav a {
            padding: 8px 8px 8px 32px;
            text-decoration: none;
            font-size: 25px;
            color: #E9EEE7;
            display: block;
            transition: 0.3s;
        }

        #mySidenav a:hover {
            color: #f1f1f1;
        }

        #mySidenav .closebtn {
            position: absolute;
            top: 0;
            right: 25px;
            font-size: 36px;
            margin-left: 50px;
        }

        /* On mouse-over */
        .sidenav a:hover, .dropdown-btn:hover {
        color: #f1f1f1;
        }

        /* Add an active class to the active dropdown button */
        .active {
          background-color: #b7b9b6;
          color: white;
        }

        /* Dropdown container (hidden by default). Optional: add a lighter background color and some left padding to change the design of the dropdown content */
        .dropdown-container {
          display: none;
          background-color: #262626;
          padding-left: 8px;
        }

        /* Optional: Style the caret down icon */
        .fa-caret-down {
          float: right;
          padding-right: 8px;
        }

        /* Some media queries for responsiveness */
        @media screen and (max-height: 450px) {
          .sidenav {padding-top: 15px;}
          .sidenav a {font-size: 18px;}
        }

        .fa-shopping-cart {
            font-size: 24px;
            color: lightgrey;
            margin-right: 5px; /* Adjust margin for better spacing */
            border: none !important;
            outline: none !important;
            box-shadow: none !important;
        }

        .container-fluid {
            display: flex;
            align-items: center;
            justify-content: flex-start;
        }

        .container-fluid span,
        .container-fluid a.navbar-brand {
            margin: 0; /* Remove margin between "Categories" and "Nile" */
        }

        a.navbar-brand {
            font-size: 24px;
            margin-left: 5px;
        }

        .navbar-brand {
            margin-right: 0;
        }

        .container-fluid span {
            font-size: 30px;
            cursor: pointer;
            margin-right: 5px;
        }

    </style>
</head>

<body>

<nav class="navbar navbar-custom navbar-expand-lg" style="font-family: sans-serif">
    <div id="mySidenav" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      <a href="javascript:void(0)" class="dropdown-btn">Clothing & Accessories</a>
        <div class="dropdown-container">
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=2 %}">Men's Clothing</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=3 %}">Women's Clothing</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=4 %}">Children's Clothing</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=5 %}">Accessories</a>
        </div>
      <a href="#" class="dropdown-btn">Health & Beauty</a>
        <div class = "dropdown-container">
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=7 %}">Skin & Hair Care</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=6 %}">Makeup</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=8 %}">Supplements</a>
        </div>
      <a href="#" class = "dropdown-btn">Electronics</a>
        <div class="dropdown-container">
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=9 %}">Smartphones & Accessories</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=10 %}">Computers & Accessories</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=15 %}">Audio & TV</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=16 %}">Photography</a>
      </div>
      <a href="#" class = "dropdown-btn">Home & Garden</a>
        <div class="dropdown-container">
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=11 %}">Home Decor</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=12 %}">Furniture</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=13 %}">Gardening</a>
        <a href="{% url 'Nile:subcategory_detail' subcategory_id=14 %}">Bed & Bath</a>
      </div>
    </div>


        <div class="container-fluid d-flex">
            <span class="text-light me-4" style="font-size: 20px" onclick="openNav()">&#9776; Categories</span>
            <a class="navbar-brand fs-1 fw-bold me-auto" href="{% url 'Nile:index' %}" style="font-size:24px">Nile</a>
        </div>
         <div>
            <ul class="nav navbar-nav ml-auto">
                    {% if user.is_authenticated %}
                        <li><a class="nav-link navbar-brand fs-6 me-auto" href="#"><span class="glyphicon glyphicon-log-in"></span>Account</a></li>
                        <li><a class="nav-link navbar-brand fs-6 me-auto" href="{% url 'Nile:order_list' %}"><span class="glyphicon glyphicon-log-in"></span>Orders</a></li>
                        <li><a class="nav-link navbar-brand fs-6 me-auto" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Logout</a></li>

                        {% if user.is_superuser %}
                            <li class="nav-item dropdown">
                                <a class="nav-link navbar-brand dropdown-toggle fs-6" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Retailer Functions
                                </a>
                                <ul class="dropdown-menu">
                                    <li><a class="dropdown-item" href="{% url 'Nile:item_create'%}">Add Item</a></li>
                                </ul>
                            </li>
                        {% endif %}

                    {% else %}
                        <li><a class="nav-link navbar-brand fs-6" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Login</a>
                        </li>
                        <li><a class="nav-link navbar-brand fs-6" href="{% url 'register' %}"><span class="glyphicon glyphicon-log-in"></span>Sign Up</a>
                        </li>
                    {% endif %}

                    <li><a href={% url "cart:cart_detail" %}><button class="fa fa-shopping-cart" style="font-size:24px;margin-top:10px;color: #000000"></button></a></li>

            </ul>
        </div>
</nav>

<div id="mySidenav">
    <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
    <!-- Add your sidebar content here -->
</div>

<div class="container">
    {% if user.is_authenticated %}
        Welcome, {{ user.first_name }} {{ user.last_name }}
    {% endif %}
</div>

<div class="container">
    <br/>
    {% block content %}
    {% endblock %}
</div>

<!-- Rest of your HTML content goes here -->

<!-- JavaScript functions for sidebar -->
<script>
var dropdown = document.getElementsByClassName("dropdown-btn");
var i;

for (i = 0; i < dropdown.length; i++) {
    dropdown[i].addEventListener("click", function () {
        this.classList.toggle("active");
        var dropdownContent = this.nextElementSibling;
        if (dropdownContent.style.display === "block") {
            dropdownContent.style.display = "none";
        } else {
            dropdownContent.style.display = "block";
        }
    });
}
    function openNav() {
        document.getElementById("mySidenav").style.width = "250px";
    }

    function closeNav() {
        document.getElementById("mySidenav").style.width = "0";
    }

</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js"
A        integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN"
        crossorigin="anonymous">
</script>

Nile/templates/Nile/category_detail.html
{{% extends 'Nile/base.html' %}

{% block title %}{{ category.name }}{% endblock %}

{% block content %}
  <h2>{{ category.name }}</h2>
  <p>{{ category.description }}</p>

  <h3>Subcategories</h3>
  <ul>
    {% for subcategory in category.subcategory_set.all %}
      <li><a href="{% url 'Nile:subcategory_detail' pk=subcategory.pk %}">{{ subcategory.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

Nile/templates/Nile/index.html
{% extends 'Nile/base.html' %}

{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for item in recommended_items %}
            <div class="col">
                <div class="card">
                    <img src="{{ item.image.url }}" alt="avatar" style="width:100%">
                    <div class="container">
                        <h4><b><a href="{% url 'Nile:item_detail' item.id %}">{{ item.name }}</a></b></h4>
                        <p>Description: {{ item.description }}</p>
                        <p>Category: {{ item.category }}</p>
                        <p>Subcategory: {{ item.subcategory }}</p>
                        <p>Price: ${{ item.price }}</p>
                        <p>Quantity: {{ item.quantity }}</p>
                        <form action="{% url "cart:cart_add" item.id %}" method="post">
                            {{ cart_product_form }}
                            {% csrf_token %}
                            <input type="submit" value="Add to cart">
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Nile/templates/Nile/item_detail.html
{% extends 'Nile/base.html' %}

{% load static %}
{% block content %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/item_detail.css' %}">
    <title>Your Page Title</title>
</head>

<div class="container">
  <div class="row">
    <div class="col-md-5">
          <img class="img-fluid" src="{{ item.image.url }}" width="100%"  alt="image of a black formal dress">
    </div>
    <div class="col-md-6">
      <h2>{{ item.name }}</h2>
      <p>{{ item.description }}</p>
      <p>Price: ${{ item.price }}</p>
      <p>Availability:
          {% if item.availability == 'a' %}
              Available
          {% else %}
              Out of Stock
      {% endif %}</p>
      {% if item.availability == 'a' %}
          <form action="{% url "cart:cart_add" item.id %}" method="post">
      {{ cart_product_form }}
      {% csrf_token %}
      <input type="submit" value="Add to cart">
    </form>
      {% endif %}
    </div>
  </div>
  <hr>
</div>
{% endblock %}

Nile/templates/Nile/item_form.html
{% extends "Nile/base.html" %}
{% load crispy_forms_tags %}
{% load crispy_forms_filters %}

{% block content %}
    {% if perms.nile.create_item or perms.nile.edit_item %}
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Submit"/>
        </form>
    {% else %}
        You do not have permission to access this feature
        <a href="{% url 'Nile:index' %}">Home</a>
    {% endif %}
{% endblock %}

Nile/templates/Nile/order_create.html
{% extends "Nile/base.html" %}

{% block title %}
  Checkout
{% endblock %}

{% block content %}
  <h1>Checkout</h1>

  <div class="order-info">
    <h3>Your order</h3>
    <ul>
      {% for item in cart %}
        <li>
          {{ item.quantity }}x {{ item.product.name }}
          <span>${{ item.total_price }}</span>
        </li>
      {% endfor %}
    </ul>
    <p>Total: ${{ cart.get_total_price }}</p>
  </div>

  <form action="." method="post" class="order-form">
    {{ form.as_p }}
    <p><input type="submit" value="Place order"></p>
    {% csrf_token %}
  </form>
{% endblock %}

Nile/templates/Nile/order_created.html
{% extends "Nile/base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <div>
        <h1>Thank you</h1>
        <p>Your order has been successfully completed. Your order number is <strong>{{ order_id }}</strong>.</p>
    </div>
    <br>
    <div>
        <a href="{% url "Nile:index" %}" class="button light">Continue shopping</a>
        <a href="{% url "Nile:order_list" %}" class="button light">Your Orders</a>
    </div>
{% endblock %}

Nile/templates/Nile/order_list.html
{% extends 'Nile/base.html' %}

{% block content %}
<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for order in orders %}


            <h1>Order {{ order.id }}</h1>
            <table>
              <tr>
                <th>Created</th>
                <td>{{ order.created }}</td>
              </tr>
              <tr>
                <th>Customer</th>
                <td>{{ order.first_name }} {{ order.last_name }}</td>
              </tr>
              <tr>
                <th>E-mail</th>
                <td><a href="mailto:{{ order.email }}">{{ order.email }}</a></td>
              </tr>
              <tr>
                <th>Address</th>
                <td>{{ order.address }}, {{ order.postal_code }} {{ order.city }}</td>
              </tr>
              <tr>
                <th>Total amount</th>
                <td>${{ order.get_total_cost }}</td>
              </tr>
              <tr>
                <th>Status</th>
                <td>{% if order.paid %}Paid{% else %}Pending payment{% endif %}</td>
              </tr>
              <tr>
                <th></th>
                <td><a href="{% url 'Nile:admin_order_pdf' order.id %}">Generate PDF invoice</a></td>
              </tr>
            </table>

            <div class="module">
              <h2>Items bought</h2>
              <div class="tabular">
                <table style="width:100%">
                  <thead>
                    <tr>
                      <th>Product</th>
                      <th>Price</th>
                      <th>Quantity</th>
                      <th>Total</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for item in order.items.all %}
                      <tr class="row{% cycle "1" "2" %}">
                        <td>{{ item.product.name }}</td>
                        <td class="num">${{ item.price }}</td>
                        <td class="num">{{ item.quantity }}</td>
                        <td class="num">${{ item.get_cost }}</td>
                      </tr>
                    {% endfor %}
                    <tr class="total">
                      <td colspan="3">Total</td>
                      <td class="num">${{ order.get_total_cost }}</td>
                    </tr>
                  </tbody>
                </table>
              </div>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Nile/templates/Nile/subcategory_detail.html
{% extends 'Nile/base.html' %}

{% block content %}
  <h2>{{ subcategory.name }}</h2>

  {% if items %}
    <ul>
      {% for item in items %}
        <li>
          <h3>{{ item.name }}</h3>
          <p>{{ item.description }}</p>
          <p>Price: ${{ item.price }}</p>
          <div class="col-md-5">
            <img class="img-fluid" src="{{ item.image.url }}" width="100%" >
          </div>

          <!-- Add more details as needed -->
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No items available in this subcategory.</p>
  {% endif %}
{% endblock %}